#Experiment - 8
#Title-EDA tools
##Name-Bedang das
##PRN-25070123031
##Batch-A2


In [ ]:
#Importing the array
import numpy as np
a=np.array([10,20,30,40])
b=np.array([[1,2,3],[4,5,6]])
print(a)
print(b)


[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [ ]:
#Dimension of array
print("The Dimension of a array is ",a.ndim)
print("The dimension of b array is ",b.ndim)

print("How may element are there (cause it is one-dimension)",a.shape)
print("How many rows and columns are there (cause it is a two-dimentional array",b.shape)

print("the Data type of A is",a.dtype)
print("The Data type of B is ",b.dtype)



The Dimension of a array is  1
The dimension of b array is  2
How may element are there (cause it is one-dimension) (4,)
How many rows and columns are there (cause it is a two-dimentional array (2, 3)
the Data type of A is int64
The Data type of B is  int64


In [ ]:
#

In [ ]:
# check
import numpy as np
np.ones((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:

np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

np.arange(1,10,2)
array=np.arange(1,10,2)
print(array)

In [ ]:
np.arange(1,10,2)
array=np.arange(1,10,2)
print(array)

[1 3 5 7 9]


In [ ]:
c=a*2
d=a+5

print(c)
print(d)


#Calculating mean
print("The mean for a is ",np.mean(a))
print("The median is ",np.median(a))

print("the mean for b is ",np.mean(b))
print("the median for b is ",np.median(b))

print("The minimum value of a is",np.min(a))
print("The maximum value of a is",np.max(a))
print("The minimum value of b is",np.min(b))
print("The maximum value of b is",np.max(b))

print("The sum of all values a is :",np.sum(a))
print("The sum of all values b is :",np.sum(b))



[20 40 60 80]
[15 25 35 45]
The mean for a is  25.0
The median is  25.0
the mean for b is  3.5
the median for b is  3.5
The minimum value of a is 10
The maximum value of a is 40
The minimum value of b is 1
The maximum value of b is 6
The sum of all values a is : 100
The sum of all values b is : 21
